extends Node

const MONTHLY_ROSTER_WORK_POLICY = preload("res://scripts/systems/monthly_roster_work_policy.gd")


func _ready() -> void:
	var contract := MONTHLY_ROSTER_WORK_POLICY.get_contract()
	assert(contract.get("status") == "frozen")
	assert(contract.get("authority") == "monthly_roster_work_policy")
	assert(contract.get("period") == "month")
	assert(contract.get("process_frequency") == "exactly_once_per_closed_month")
	assert(contract.get("migration_mode") == "one_legacy_turn_equals_one_monthly_turn")
	assert(contract.get("work_outputs_enabled") == true)
	assert(contract.get("training_progress_enabled") == true)
	assert(contract.get("fatigue_mutation_enabled") == true)
	assert(contract.get("injury_auto_recovery_enabled") == true)
	assert(contract.get("injury_treatment_enabled") == true)
	assert(contract.get("fatigue_combat_availability_enabled") == true)
	assert(int(contract.get("mining_fatigue", 0)) == 8)
	assert(int(contract.get("security_fatigue", 0)) == 4)
	assert(int(contract.get("espionage_fatigue", 0)) == 6)
	assert(int(contract.get("training_fatigue", 0)) == 7)
	assert(int(contract.get("fatigue_combat_limit", 0)) == 90)
	assert(int(contract.get("slave_promotion_training_threshold", 0)) == 100)
	assert(contract.get("legacy_daily_formula_allowed") == false)
	assert(contract.get("legacy_weekly_formula_allowed") == false)
	assert(contract.get("legacy_values_scaled_for_months") == false)
	assert(contract.get("invent_monthly_values_allowed") == false)
	assert(contract.get("save_version_change_required") == false)
	print("Monthly roster work policy frozen contract: OK")
	get_tree().quit(0)
