extends Node

func run() -> void:
    var hub := FileAccess.get_file_as_string("res://scripts/ui/finca_hub_controller.gd")
    var screen := FileAccess.get_file_as_string("res://scripts/ui/finca_screen.gd")
    var buildings := FileAccess.get_file_as_string("res://data/buildings.json")
    var project := FileAccess.get_file_as_string("res://project.godot")

    assert(hub.contains("const BUILDING_SYSTEMS"))
    assert(hub.contains('"dominus_house": "campana"'))
    assert(hub.contains('"barracks": "barracks"'))
    assert(hub.contains('"training_yard": "personal"'))
    assert(hub.contains('"forge": "forja"'))
    assert(hub.contains('"infirmary": "personal"'))
    assert(hub.contains('"mine": "economia"'))
    assert(not hub.contains('"private_arena": "arena"'))
    assert(not hub.contains('"kitchen": "economia"'))
    assert(screen.contains("const BUILDING_LAYOUT"))
    assert(screen.contains('"id":"beast_area"'))
    assert(screen.contains("button.pressed.connect(_on_hotspot_pressed.bind(building_id))"))
    assert(screen.contains("func _on_hotspot_pressed(building_id: String)"))
    assert(screen.contains("_open_building_modal()"))
    assert(screen.contains("func _open_selected_building()"))
    assert(buildings.contains('"id": "forge"'))
    assert(buildings.contains('"id": "barracks"'))
    assert(buildings.contains('"id": "mine"'))
    assert(buildings.contains('"id": "beast_area"'))
    assert(not buildings.contains('"id": "market"'))
    assert(not buildings.contains('"id": "kitchen"'))
    assert(not buildings.contains('"id": "private_arena"'))
    assert(not project.contains("FincaBuildingNavigationController="))
    assert(not FileAccess.file_exists("res://scripts/ui/finca_building_navigation_controller.gd"))
    print("Hosted Finca seven-facility building navigation contract: OK")
