extends Node


func run() -> void:
	var active_screen := FileAccess.get_file_as_string("res://scripts/ui/finca_screen_monthly.gd")
	var legacy_screen := FileAccess.get_file_as_string("res://scripts/ui/finca_screen.gd")
	var scene := FileAccess.get_file_as_string("res://scenes/FincaScreen.tscn")
	var hub := FileAccess.get_file_as_string("res://scripts/ui/finca_hub_controller.gd")

	assert(active_screen.contains("GameState.month_advanced.connect"))
	assert(not active_screen.contains("GameState.week_advanced.connect"))
	assert(active_screen.contains("func _open_selected_building()"))
	assert(active_screen.contains("FincaHubController.open_building_system(selected_building_id)"))
	assert(active_screen.contains("Abrir campaña"))
	assert(active_screen.contains("Entrar a barracones"))
	assert(active_screen.contains("Entrar a la forja"))
	assert(active_screen.contains("Abrir economía de la mina"))
	assert(active_screen.contains("Abrir zona de bestias"))
	assert(active_screen.contains("Cerrar mes"))
	assert(not active_screen.to_lower().contains("recuperación semanal"))
	assert(legacy_screen.contains("const BUILDING_LAYOUT"))

	assert(scene.contains('path="res://scripts/ui/finca_screen_monthly.gd"'))
	assert(scene.contains('name="Enter"') or scene.contains('name = "Enter"'))
	assert(scene.contains('text = "MES 1"'))
	assert(scene.contains('text = "Cerrar mes"'))
	assert(not scene.to_lower().contains("semana"))

	assert(hub.contains("func get_building_system_id"))
	assert(hub.contains("func open_building_system"))
	assert(hub.contains('"dominus_house": "campana"'))
	assert(hub.contains('"barracks": "barracks"'))
	assert(hub.contains('"training_yard": "barracks"'))
	assert(hub.contains('"forge": "forja"'))
	assert(hub.contains('"infirmary": "personal"'))
	assert(hub.contains('"mine": "economia"'))
	assert(hub.contains('"beast_area": "bestias"'))
	assert(hub.contains('"bestias": "res://scenes/BeastAreaScreen.tscn"'))
	assert(not hub.contains('"kitchen": "economia"'))
	assert(not hub.contains('"private_arena": "arena"'))
	print("Hosted Finca monthly contextual access contract: OK")
